apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-consumer-deployment
  namespace: confluent
  labels:
    app: kafka-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-consumer
  template:
    metadata:
      labels:
        app: kafka-consumer
    spec:
      containers:
        - name: kafka-consumer
          image: m11registry.azurecr.io/consumer:latest
#          image: aliaksandrmikhailik/kafka-consumer:latest
